services:
    campaignchain.location.website.page.job.cta:
        class: CampaignChain\Location\WebsiteBundle\Service\PageCTAJob
        arguments: [ @doctrine.orm.entity_manager, @service_container ]